name:                 lr-acts
version:              0.0.1
github:               "AliceRixte/lr-acts"
license:              BSD-3-Clause
author:               "Alice Rixte"
maintainer:           "alice.rixte@u-bordeaux.fr"
category:             Algebra, Math, Data
synopsis:             Left and right actions, semidirect products and torsors

extra-source-files:
- README.md

extra-doc-files:
- CHANGELOG.md


# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/AliceRixte/lr-acts/blob/main/README.md>

dependencies:
- base >= 4.18 && < 5
- groups >= 0.5 && < 0.6
- data-default >= 0.7 && < 0.9

ghc-options:
  - -Wall
  - -threaded

tested-with: GHC == 9.8.2

library:
  ghc-options:
  - -fprint-potential-instances
  source-dirs: src

tests:
  lr-acts-test:
    main:                Spec.hs
    dependencies:
    - lr-acts
    - hspec >= 2.11
    - QuickCheck >= 2.14.3
    source-dirs:         test
    ghc-options:
      - -rtsopts
      - -with-rtsopts=-N

benchmarks:
  lr-acts-bench:
    main: Main.hs
    dependencies:
      - lr-acts
      - criterion >= 1.6
    source-dirs: benchmark
    ghc-options:
      # - -O2  no difference between O2 and O0
      - -rtsopts
      - -with-rtsopts=-N