name:                lr-acts
version:             0.0.0
github:              "AliceRixte/pandia/lr-acts"
license:             BSD3
author:              "Alice Rixte"
maintainer:          "alice.rixte@u-bordeaux.fr"
copyright:           "BSD3"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            media

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/AliceRixte/pandia/blob/main/lr-acts#readme>

dependencies:
- base >= 4.18 && < 5
- groups >= 0.5

ghc-options:
  - -Wall
  - -threaded

tested-with: GHC ==9.8.2

library:
  ghc-options:
  - -O2
  - -fprint-potential-instances
  # default-extensions:
  # - GeneralizedNewtypeDeriving
  # - FunctionalDependencies
  # - MultiParamTypeClasses
  # - FlexibleContexts
  # - FlexibleInstances
  # - StandaloneDeriving
  # - ScopedTypeVariables
  # - UndecidableInstances
  # - MonoLocalBinds
  # - DataKinds
  # - TypeOperators
  # - TypeFamilies
  # - OverloadedLabels
  source-dirs: src

tests:
  lr-acts-test:
    main:                Spec.hs
    dependencies:
    - lr-acts
    - hspec >= 2.11
    - QuickCheck >= 2.14.3
    source-dirs:         test
    ghc-options:
      - -O0
      - -rtsopts
      - -with-rtsopts=-N

benchmarks:
  lr-acts-bench:
    main: Main.hs
    dependencies:
      - lr-acts
      - criterion >= 1.6
    source-dirs: benchmark
    ghc-options:
      - -O2
      - -rtsopts
      - -with-rtsopts=-N
  monoid-list:
    main: monoid-list.hs
    dependencies:
      - lr-acts
      - monoid-extras
      - criterion >= 1.6
    source-dirs: benchmark
    ghc-options:
      - -O2
      - -rtsopts
      - -with-rtsopts=-N